# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-08 00:42
from __future__ import unicode_literals

from django.db import migrations, models
import notes.models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='image',
            field=models.FileField(upload_to=notes.models.upload_note_image),
        ),
    ]
